players:
- id: george
  name: george
  display_names:
  - george
  plays:
  - Zinnia
- id: thomas
  name: Thomas Kolivakis
  display_names:
  - Thomas Kolivakis
  plays:
  - Zephyr
- id: nicholas
  name: Nicholas Roussos
  display_names:
  - Nicholas Roussos
  plays:
  - Sequoia
- id: kostadis
  name: Kostadis Roussos
  display_names:
  - Kostadis Roussos
  gm: true
  plays:
  - Calmer
