characters:
- name: Akritas
  sheet: docs/akritas.md
  arc_score: null
- name: Bramgrim Stoutale
  sheet: docs/bramgrim.md
  arc_score: null
- name: Daein
  sheet: docs/daien.md
  arc_score: null
- name: Felkur Oldenwood
  sheet: docs/felkur.md
  arc_score: null
