players:
- id: gabe
  name: Gabe
  display_names:
  - Gabe
  plays:
  - Zalthir
- id: joe
  name: Joe Beda
  display_names:
  - Joe Beda
  plays:
  - Thorin Giantfriend
- id: ben
  name: Ben Pfaff
  display_names:
  - Ben Pfaff
  plays:
  - Gyrgum
- id: mike
  name: Mike Hall
  display_names:
  - Mike Hall
  plays:
  - Daz
- id: kostadis
  name: Kostadis Roussos
  display_names:
  - Kostadis Roussos
  plays: []
  gm: true
