players:
- id: kostadis
  name: Kostadis Roussos
  display_names:
  - Kostadis Roussos
  plays:
  - Veyra of the Blue Candle
  - Sister Maela Dawnforge
  - Pip Thistlewick
  gm: true
- id: nikhil
  name: Nikhil Reddy
  display_names:
  - Nikhil Reddy Mettupally
  - Nikhil
  plays:
  - Zenvon Forepot
