players:
- id: wade
  name: Wade Brown
  display_names:
  - Wade Brown
  plays:
  - Vardis
- id: david
  name: David Mendenhall
  display_names:
  - David Mendenhall
  plays:
  - Orsik
- id: jared
  name: Jared Rossof
  display_names:
  - Jared Rossof
  plays:
  - Unla Key
