characters:
- name: Brewbarry
  sheet: docs/party/Brewbarry.md
  player: Stéphane Bourdeaud
  backstory: docs/Backstory - Brewbarry.md
  arc_score: docs/tracking/brewbarry-score.md
- name: Valphine
  sheet: docs/party/Valphine.md
  player: Gary Young
  backstory: docs/Backstory - Valphine Sotorra.md
  arc_score: docs/tracking/valphine-score.md
- name: Soma
  sheet: docs/party/Soma.md
  player: Wade Brown
  backstory: docs/Soma - Backstory.md
  arc_score: docs/tracking/soma-score.md
- name: Vukradin
  sheet: docs/party/Vukradin.md
  player: David Mendenhall
  arc_score: null
